feature: FunctionSupport
polestar1592/javautilities pull request #10
Opened 2020-02-16 11:02 UTC by araish

関数の部分適用やカリー化を実装しました。
本来なら独自の`Function`を作るのがいいのかもしれないですが。。。

2020-02-16 21:54 UTC, polestar1592 requested changes
引数側の `BiFunction<T, U, R>` は、型境界を指定して変性を入れたほうが良いかも。
`BiFunction<? super T, ? super U, ? extends R>`
他は良いと思います。

2020-02-16 21:55 UTC, polestar1592 commented
前言ったけど、FunctionとConsumerを合成したりSupplierとFunction, Cnsumerを合成するutilも、
あとで欲しいです！

2020-02-17 12:42 UTC, araish commented
https://github.com/polestar1592/javautilities/pull/10#pullrequestreview-359431802
ここらへんあんま自信ないんだけど、`TriFunction`には不要?

2020-02-17 13:16 UTC, araish commented
https://github.com/polestar1592/javautilities/pull/10#issuecomment-586976157
- `Supplier<T>`と`Function<T, R>`を受け取って、`Supplier<R>`を返す。
- `Function<T, R>`と`Consumer<R>`を受け取って、`Consumer<T>`を返す。
他は?

2020-02-17 14:33 UTC, polestar1592 commented
微妙な気もするけど `Supplier<T>`と`Consumer<T>`で、
`Supplier<Void>`か`Runnable`くらいが返るのはどう？

2020-02-17 14:36 UTC, polestar1592 commented
https://github.com/polestar1592/javautilities/pull/10#issuecomment-586976157
`TriFunction<? super S, ? super T,? super U, ? extends R>`
が欲しいですね

2020-02-17 15:54 UTC, polestar1592 commented
暗記のために PECS 原則なんて言葉があるらしいですよ。

2020-02-18 14:48 UTC, polestar1592 approved these changes
かんぺき

2020-02-18 20:48 UTC, merged

2020-02-19 14:39 UTC, polestar1592 commented
GJ!